pref("extensions.scriptish.aboutIsGreaseable", false);
pref("extensions.scriptish.fileIsGreaseable", false);
pref("extensions.scriptish.unmhtIsGreaseable", false);
pref("extensions.scriptish.enableCopyDownloadURL", false);
pref("extensions.scriptish.enableScriptRefreshing", true);
pref("extensions.scriptish.uninstallPreferences", true);
pref("extensions.scriptish.useBlocklist", true);
pref("extensions.scriptish.useDefaultLocale", false);
pref("extensions.scriptish.useDownloadURLForUpdateURL", false);
